// Modern Real Estate Website - Enhanced JavaScript
// Performance optimized with modern ES6+ features

// DOM Elements - Cached for performance
const elements = {
  navbar: document.querySelector(".navbar"),
  hamburger: document.querySelector(".hamburger"),
  navMenu: document.querySelector(".nav-menu"),
  navLinks: document.querySelectorAll(".nav-link"),
  themeToggle: document.querySelector(".theme-toggle"),
  adminAccessBtn: document.getElementById("adminAccessBtn"),
  adminModal: document.getElementById("adminModal"),
  addPropertyModal: document.getElementById("addPropertyModal"),
  closeButtons: document.querySelectorAll(".close"),
  tabButtons: document.querySelectorAll(".tab-btn"),
  tabContents: document.querySelectorAll(".tab-content"),
  addPropertyBtn: document.getElementById("addPropertyBtn"),
  addPropertyForm: document.getElementById("addPropertyForm"),
  cancelAddProperty: document.getElementById("cancelAddProperty"),
  contactForm: document.getElementById("contactForm"),
  searchInput: document.getElementById("searchInput"),
  searchBtn: document.getElementById("searchBtn"),
  propertyTypeFilter: document.getElementById("propertyType"),
  propertyStatusFilter: document.getElementById("propertyStatus"),
  priceRangeFilter: document.getElementById("priceRange"),
  propertiesGrid: document.getElementById("propertiesGrid"),
  adminPropertiesList: document.getElementById("adminPropertiesList"),
  adminInquiriesList: document.getElementById("adminInquiriesList"),
};

// Enhanced Properties Data
let properties = [
  {
    id: 1,
    title: "Modern 4-Bedroom Bungalow",
    description:
      "Luxurious 4-bedroom bungalow facing tarred road with excellent proximity to major places in GRA. Document: C of O.",
    location: "GRA, Ilorin, Kwara State",
    price: "₦280M",
    type: "house",
    status: "sale",
    beds: 4,
    baths: 3,
    size: "7 Plots",
    image: "bedroom.jpg",
    features: ["4 Beds", "3 Baths", "7 Plots"],
    amenities: ["C of O", "Tarred Road", "GRA Location"],
    yearBuilt: 2023,
    area: "GRA",
  },
  {
    id: 2,
    title: "Modern 5 Bedroom Home",
    description:
      "Last 85m, reason is this it comes with all 10 AC, the 27kv generator and the car porch. Total land is 4 plots, main house has 5 bedrooms, joined BQ has 2 bedrooms. It has C of O.",
    location: "Along Airport road, Ilorin, Kwara state",
    price: "₦100M",
    type: "house",
    status: "sale",
    beds: 5,
    baths: 4,
    size: "4 Plots",
    image: "servicess.jpg",
    features: ["5 Beds", "4 Plots", "10 AC", "27kv Generator"],
    amenities: ["C of O", "Car Porch", "BQ"],
    yearBuilt: 2022,
    area: "Airport Road",
  },
  {
    id: 3,
    title: "Investment Land Package",
    description:
      "This land is located near kanbi olorobo estate, Ilorin. It is a good land for investment, estate and farming activities",
    location: "Mandate Market Area, Ilorin",
    price: "₦3M",
    type: "land",
    status: "sale",
    beds: 0,
    baths: 0,
    size: "1 Plot",
    image: "landd.jpg",
    features: ["Estate Ready", "Farming Activities", "Secure"],
    amenities: ["Investment Ready", "Estate Development"],
    yearBuilt: null,
    area: "Mandate Market",
  },
  {
    id: 4,
    title: "4-Bedroom Bungalow",
    description:
      "4-bedroom bungalow on 2 plots, divided into 2-bedroom flat and room & parlor. POP ceiling, fenced with gate. Close to main road. Document: C of O.",
    location: "Power Line, Irewolede, Ilorin, Kwara State",
    price: "₦40M",
    type: "house",
    status: "sale",
    beds: 4,
    baths: 3,
    size: "2 Plots",
    image: "newprop.jpeg",
    features: ["4 Beds", "3 Baths", "2 Plots"],
    amenities: [
      "C of O",
      "POP Ceiling",
      "Fenced with Gate",
      "Close to Main Road",
    ],
    yearBuilt: null,
    area: "Irewolede",
  },
  {
    id: 5,
    title: "Modern Home for Sale",
    description:
      "Modern Duplex and solid structure with high commercial structures, located at tanke area.",
    location: "University Road, tanke garage area",
    price: "₦40M",
    type: "house",
    status: "sale",
    beds: 3,
    baths: 2,
    size: "1 Plot",
    image: "property.jpg",
    features: ["Duplex", "Balcony", "Commercial"],
    amenities: ["Solid Structure", "High Commercial Value"],
    yearBuilt: 2020,
    area: "Tanke",
  },
  {
    id: 6,
    title: "Two Story Buildings",
    description: "Two storey buildings, each 4 spacious flats and each 100M.",
    location: "Sawmill road, Ilorin",
    price: "₦100M",
    type: "house",
    status: "sale",
    plots: "3 each",
    flats: "4 each",
    size: "5 Plots",
    image: "prop.jpg",
    features: ["3 Plots each", "2 Story Building", "4 flats each"],
    amenities: ["Multiple Plots", "Genuine documents", "Near Road"],
    yearBuilt: 2018,
    area: "Sawmill",
  },
];

// Sample Inquiries Data
let inquiries = [
  {
    id: 1,
    name: "John Doe",
    email: "john@example.com",
    phone: "08012345678",
    message: "I am interested in property ID 1. Please contact me.",
    date: "2023-10-26",
    status: "new",
  },
];
 